ComunidadDePracticaMVC/ComunidadDePracticaMVC/Controllers/CorreoController.cs
using ComunidadDePracticaMVC.Models;
using System;
using System.Web.Mvc;
using System.Net.Mail;

namespace ComunidadDePracticaMVC.Controllers
{
    public class CorreoController : Controller
    {
        // GET: Correo
        public ActionResult Index()
        {

            return View();
        }

        public JsonResult EnviarCorreo(CorreoModel correo) {
            // Specify the from and to email address
            MailMessage mailMessage = new MailMessage
                ("comunidadDePracticaGrupo3@gmail.com", correo.EmailTo);
            mailMessage.IsBodyHtml = true;
            mailMessage.Body = "<div>"+ correo.EmailBody + "</div>"+"<p> -Enviado desde Comunidad de Práctica Grupo 3</p>";
            mailMessage.Subject = correo.Sender + " en Comunidad De Práctica: " + correo.Subject;
            
            SmtpClient smtpClient;

            string nombreGrupo3 = "comunidadDePracticaGrupo3@gmail.com";
            string passwordGrupo3 = "comunidadPractica3.pass";

            try
            {
                // No need to specify the SMTP settings as these 
                // are already specified in web.config
                smtpClient = new SmtpClient("smtp.gmail.com");
                smtpClient.EnableSsl = true;
                smtpClient.UseDefaultCredentials = false;
                smtpClient.Port = 587;
                smtpClient.Credentials = new System.Net.NetworkCredential(nombreGrupo3, passwordGrupo3);
                smtpClient.Send(mailMessage);
                smtpClient.Dispose();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception caught in CreateTestMessage2(): {0}",
                    ex.ToString());
                JsonResult errorMessage = Json(new
                {
                    to = correo.EmailTo,
                    subject = correo.Subject,
                    body = correo.EmailBody,
                    returnMessage = "Error: Correo no pudo ser enviado.",
                    newUrl = Url.Action("Index", "Home")
                }
                );
                return errorMessage;
            }
           
            JsonResult result = Json(new
            {
                to = correo.EmailTo,
                subject = correo.Subject,
                body = correo.EmailBody,
                responseMessage = "Correo enviado.",
                newUrl = Url.Action("Index", "Home")
            }
                );
            return result;
        }
    }
}

ComunidadDePracticaMVC/ComunidadDePracticaMVC/Controllers/RevisionesController.cs
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ComunidadDePracticaMVC.Models;
using ComunidadDePracticaMVC.Services;
using Newtonsoft.Json;

namespace ComunidadDePracticaMVC.Controllers
{
    public class RevisionesController : Controller
    {
        public ActionResult ArticulosRequierenRevision()
        {
            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"].ToString();
            }
            ViewBag.categoria = "";
            ViewBag.revisiones = new RevisionesModel();
            RevisionesService servicioRevisiones = new RevisionesService();
            if (User.Identity.IsAuthenticated)
            {
                string correo = User.Identity.Name.ToString();
                UsuarioService servicioUsuarios = new UsuarioService();
                var datos = servicioUsuarios.GetDatosMiembro(correo);
                ViewBag.categoria = datos[0];
                ViewBag.revisiones = servicioRevisiones.ObtenerArticulosEnRevision();
            }
            else
            {
                return RedirectToAction("~/AccessDenied");
            }

            return View();
        }

        [Authorize]
        public ActionResult MisArticulosRevision()
        {
            ViewBag.exitoAutorizacion = false;
            ViewBag.revisiones = new RevisionesModel();
            RevisionesService servicioRevisiones = new RevisionesService();
            if (CookieHandler.AuthorizeRole(Request.Cookies[FormsAuthentication.FormsCookieName], "Núcleo,Coordinador"))
            {
                if (TempData["Message"] != null)
                {
                    ViewBag.Message = TempData["Message"].ToString();
                    
                }
                ViewBag.Acceso = "Se pudo entrar";
                ViewBag.exitoAutorizacion = true;
                var auth = Request.Cookies[FormsAuthentication.FormsCookieName];
                string correo = FormsAuthentication.Decrypt(auth.Value).Name;
                ViewBag.correo = correo;
                ViewBag.revisiones = servicioRevisiones.ObtenerArticulosAsignadosRevisionAMiembro(correo);

            }
            else
            {
                return RedirectToAction("~/AccessDenied");
            }

            return View();
        }

        [Authorize]
        public ActionResult MisArticulosColaboracion() {
            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"].ToString();
            }
            ViewBag.categoria = "";
            return View();
        }

        [HttpGet]
        public JsonResult ArticulosAutorColaboracion(int pageNumber, int pageSize, string correo)
        {
            RevisionesService serviceRev = new RevisionesService();
            List<ArticuloModel> articuloList = serviceRev.GetSolicitudesDeColaboracion(pageNumber, pageSize, correo);
            return Json(articuloList, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult SolicitarColaboracion(int articuloId)
        {
            ViewBag.categoria = "";
            ViewBag.revisiones = new RevisionesModel();
            RevisionesService servicioRevisiones = new RevisionesService();
            if (User.Identity.IsAuthenticated)
            {
                string correo = User.Identity.Name.ToString();
                UsuarioService servicioUsuarios = new UsuarioService();
                var datos = servicioUsuarios.GetDatosMiembro(correo);
                ViewBag.categoria = datos[0];
                if (ViewBag.categoria == "Coordinador")
                {
                    //ejecuta metodo para enviar solicitud


                    bool exito = servicioRevisiones.PedirColaboracionATodos(articuloId);

                    if (exito)
                    {
                        @TempData["Message"] = "Se ha enviado la solicitud";
                    }
                    else
                    {
                        @TempData["Message"] = "Falló la operación, intente más tarde";
                    }
                }
                ViewBag.revisiones = servicioRevisiones.ObtenerArticulosEnRevision();

                return RedirectToAction("ArticulosRequierenRevision");
            }
            else
            {
                return RedirectToAction("ArticulosRequierenRevision");
            }
        }

        [Authorize]
        public ActionResult AceptarColaboracion(int articuloId)
        {

        
            if (CookieHandler.AuthorizeRole(Request.Cookies[FormsAuthentication.FormsCookieName], "Núcleo,Coordinador"))
            {
                RevisionesService servicioRevisiones = new RevisionesService();
                bool exito = servicioRevisiones.AceptarColaboracion(articuloId, User.Identity.Name);
                if (exito)
                {
                    @TempData["Message"] = "Se aceptó la colaboración.";
                }
                else
                {
                    @TempData["Message"] = "Falló la operación.";
                }
                return RedirectToAction("MisArticulosColaboracion");
            }
            else
            {
                return RedirectToAction("~/AccessDenied");
            }

            
        }

        [Authorize]
        public ActionResult RechazarColaboracion(int articuloId)
        {

            if (CookieHandler.AuthorizeRole(Request.Cookies[FormsAuthentication.FormsCookieName], "Núcleo,Coordinador"))
            {
                RevisionesService servicioRevisiones = new RevisionesService();
                bool exito = servicioRevisiones.RechazarColaboracion(articuloId, User.Identity.Name);
                if (exito)
                {
                    @TempData["Message"] = "Se rechazó la colaboración.";
                }
                else
                {
                    @TempData["Message"] = "Falló la operación.";
                }
                return RedirectToAction("MisArticulosColaboracion");
            }
            else
            {
                return RedirectToAction("~/AccessDenied");
            }
        }

        [Authorize]
        public ActionResult CalificarArticulo(int articuloId)
        {

            if (true /*TODO revisar si el aritculo le corresponde al calificador*/)
            {
                ArticuloService servicioArticulo = new ArticuloService();
                ModelState.Clear();
                if (User.Identity.IsAuthenticated)
                {
                    ViewBag.Articulo = servicioArticulo.GetInfoArticulo(articuloId);
                }
                return View();

            }
            else 
            {
                return RedirectToAction("~/AccessDenied");
            }
        }

        //Envia la revision del articulo
        [HttpPost]
        [Authorize]
        public ActionResult EnviarRevision(int articuloId, FormularioModel model)
        {

            HttpCookie authCookie = Request.Cookies[FormsAuthentication.FormsCookieName];
            if (authCookie != null)
            {
                FormsAuthenticationTicket authTicket = FormsAuthentication.Decrypt(authCookie.Value);
                CookieModel cookieInfo = JsonConvert.DeserializeObject<CookieModel>(authTicket.UserData);
                string correo = authTicket.Name;
                int calificacion = cookieInfo.Merito * (model.OpinionGeneral + model.Contribucion + model.Forma);

                RevisionesService servicioRevisiones = new RevisionesService();
                bool exito = servicioRevisiones.AsignarCalificacion(articuloId, correo, calificacion, model);
                if (exito)
                {
                    @TempData["Message"] = "Revisión enviada.";
                }
                else
                {
                    @TempData["Message"] = "Error al enviar la revisión.";
                }
                return RedirectToAction("MisArticulosRevision");
            }
            else
            {
                return RedirectToAction("~/AccessDenied");

            }

        }

        public ActionResult ArticulosRequierenRevisores()
        {
            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"].ToString();
            }
            ViewBag.categoria = "";
            ViewBag.revisiones = new RevisionesModel();
            RevisionesService servicioRevisiones = new RevisionesService();
            if (User.Identity.IsAuthenticated)
            {
                string correo = User.Identity.Name.ToString();
                UsuarioService servicioUsuarios = new UsuarioService();
                var datos = servicioUsuarios.GetDatosMiembro(correo);
                ViewBag.categoria = datos[0];
                ViewBag.revisiones = servicioRevisiones.ObtenerArticulosRequierenRevisores();
            }
            return View();
        }

        public ActionResult DecidirRevisores(int articuloId)
        {
            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"].ToString();
            }
            ViewBag.categoria = "";
            ViewBag.revisiones = new RevisionesModel();
            RevisionesService servicioRevisiones = new RevisionesService();
            if (User.Identity.IsAuthenticated)
            {
                string correo = User.Identity.Name.ToString();
                UsuarioService servicioUsuarios = new UsuarioService();
                var datos = servicioUsuarios.GetDatosMiembro(correo);
                ViewBag.categoria = datos[0];
            }
            ViewBag.articuloId = articuloId;
            ViewBag.servicioRev = servicioRevisiones;
            return View(servicioRevisiones.ObtenerPosiblesRevisores(articuloId));
        }

ComunidadDePracticaMVC/ComunidadDePracticaMVC/Views/Shared/_Layout.cshtml
@using System;
@using System.Collections.Generic;
@using System.Data;
@using System.Data.SqlClient;
@using System.Configuration;
@using System.Linq;
@using System.Web;
@using ComunidadDePracticaMVC.Models;
@using System.IO;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/estilos/style.css">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/Content/estilos/estilos.css">



</head>

<body>

    <nav class="topnav navbar navbar-fixed-top main-font">
        <div class="container-fluid">
            <div class="container">

                <div id="navbar " class="navbar-collapse collapse">

                    <ul class="nav navbar-nav navbar-left">
                        <li><a><i class="fa fa-gg-circle fa-lg" style="margin-right: -12px;"></i></a></li>
                        <li>@Html.ActionLink("Comunidad De Practica", "Index", "Home")</li>
                    </ul>
                    <!--diferentes vistas dependiendo de si hay usuario logeado -->
                    @Html.Partial("_LayoutTopNav")
                </div><!--/.nav-collapse -->
            </div>

        </div><!--/.container-fluid -->
    </nav>

    <div class="container my-body-content main-font ">
        <div class="row my-row">
            <div class="col-md-3 my-col">
                <!-- Sidebar -->
                <div id="sidebar-wrapper" class="shadow">

                    <ul class="sidebar-nav">
                        <!--diferentes vistas dependiendo de si hay usuario logeado -->
                        @Html.Partial("_LayoutSideBar")
                        <!-- Por ahora ya que no hay usuarios-->
                        <!-- Por ahora  ya que no hay usuarios-->
                        <li style="color: #999999; padding: 1rem;"> Busqueda por tópico  </li>
                        <li>

                            @*<div style="padding-left: 10px; padding-right: 10px;">
                                <div class="search-bar">
                                    <input id="tableSearch" class="search-text" type="text" style="font-size: 1.3rem;" placeholder="Busque aqui.">
                                </div>

                            </div>
                            <script type="text/javascript">
                                var input = document.getElementById("tableSearch");
                                input.addEventListener("keyup", function (event) {
                                    if (event.keyCode === 13) {
                                        var url = '@Url.Action("    o", new { hilera ="VAL"})';
                                        url = url.replace("VAL", document.getElementById("tableSearch").value);

                                        //alert(url);
                                        window.location = url;
                                    }
                                });
                            </script>*@

                        </li>

                        @*<li class="sidebar-divider"></li>*@

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tópicos<span class="caret"></span></a>
                            <ul class="dropdown-content">
                                <li><a href="@Url.Action("Busqueda", "Articulo", new { hilera ="Biología"})">Biología</a></li>
                                <li><a href="@Url.Action("Busqueda", "Articulo", new { hilera ="Educación"})">Educación</a></li>
                                <li><a href="@Url.Action("Busqueda", "Articulo", new { hilera ="Filosofía"})">Filosofía</a></li>
                                <li><a href="@Url.Action("Busqueda", "Articulo", new { hilera ="Física"})">Física</a></li>
                                <li><a href="@Url.Action("Busqueda", "Articulo", new { hilera ="Ingeniería"})">Ingeniería</a></li>
                                <li><a href="@Url.Action("Busqueda", "Articulo", new { hilera ="Matemática"})">Matemaática</a></li>
                                <li><a href="@Url.Action("Busqueda", "Articulo", new { hilera ="Medicina"})">Medicina</a></li>
                            </ul>
                        </li>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="sidebar-divider"></li>
                            <li>@Html.ActionLink("Filtrar miembros", "FiltrarMiembro", "FiltrarMiembro", new { correo = User.Identity.Name, graficado = 0 }, htmlAttributes: new { title = "Filtrar" })</li>
                        }
                        <li class="sidebar-divider"></li>
                        <li>@Html.ActionLink("Página Principal", "Index", "Home", routeValues: null, htmlAttributes: new { title = "Devolverse a la página principal" })</li>
                        <li>@Html.ActionLink("FAQ", "FAQ", "faq", routeValues: null, htmlAttributes: new { title = "Preguntas frecuentes" })</li>
                    </ul>



                </div>
                <!-- /#sidebar-wrapper -->
            </div>
            <div class="col-md-9 my-col">

                <!-- old body with class container body  -->
                @RenderBody()

            </div>
        </div>
    </div>


</body>
</html>

ComunidadDePracticaMVC/ComunidadDePracticaMVC/Views/Shared/_LayoutSideBar.cshtml
@if (User.Identity.IsAuthenticated)
{
    // Retrieves the cookie that contains your custom FormsAuthenticationTicket.
    HttpCookie authCookie = HttpContext.Current.Request.Cookies[FormsAuthentication.FormsCookieName];
    // Decrypts the FormsAuthenticationTicket that is held in the cookie's .Value property.
    FormsAuthenticationTicket authTicket = FormsAuthentication.Decrypt(authCookie.Value);
    string nombreUsuario = (Json.Decode(authTicket.UserData))["Nombre"];
    string categoria = (Json.Decode(authTicket.UserData))["Categoria"];

    <p class="sidebar-title">@nombreUsuario</p>
    <li> @Html.ActionLink("Mi perfil", "DesplegarUsuario", "Usuario", new { correo = User.Identity.Name }, htmlAttributes: new { title = "Acceder a mi perfil" }) </li>
    <!--<li> <a href="#"> Crear Articulo </a> </li>-->
    <!--<li class="sidebar-divider"></li>-->
    if (categoria == "Núcleo" || categoria == "Coordinador")
    {
        <li>@Html.ActionLink("Revisión de Artículos", "MisArticulosRevision", "Revisiones", null, htmlAttributes: new { title = "Acceder a revisar artículos" })</li>
        if (categoria == "Coordinador")
        {
            <li>@Html.ActionLink("Publicación de Artículos", "ArticulosRequierenRevision", "Revisiones", null, htmlAttributes: new { title = "" })</li>
        }
        <li>@Html.ActionLink("Filtrar miembros", "FiltrarMiembro", "FiltrarMiembro", new { correo = User.Identity.Name, graficado = 0 }, htmlAttributes: new { title = "Filtrar" })</li>
    }
    <li class="sidebar-divider"></li>
    <li> @Html.ActionLink("Mis Articulos", "MisArticulos", "Usuario", null, htmlAttributes: new { title = "Mis artículos" })</li>
    <li> @Html.ActionLink("Crear Artículo Largo", "Index", "ArticuloLargo") </li>
    <li> @Html.ActionLink("Crear Artículo Corto", "Create", "Articulo") </li>
    <li class="sidebar-divider"></li>
    if (categoria == "Coordinador")
    {

        <li> @Html.ActionLink("Ver Miembros", "UsuariosComunidad", "Usuario") </li>
        <li> @Html.ActionLink("Asignar Meritos", "ArticulosCalificados", "Articulo") </li>

    }
    <li class="sidebar-divider"></li>
}

ComunidadDePracticaMVC/ComunidadDePracticaMVC/Views/Shared/_LayoutTopNav.cshtml
@if (User.Identity.IsAuthenticated)
{
    // Retrieves the cookie that contains your custom FormsAuthenticationTicket.
    HttpCookie authCookie = HttpContext.Current.Request.Cookies[FormsAuthentication.FormsCookieName];
    // Decrypts the FormsAuthenticationTicket that is held in the cookie's .Value property.
    FormsAuthenticationTicket authTicket = FormsAuthentication.Decrypt(authCookie.Value);
    string nombreUsuario = (Json.Decode(authTicket.UserData))["Nombre"];
    var correo = User.Identity.Name;

    <script type="text/javascript">

        $(document).ready(function () {

            var email = '@User.Identity.Name';
            var initials ="*";
            if (email.length > 1) {
                initials = (email.substring(0, 2)).toUpperCase();
            }
            else if (email.length > 0) {
                initials = (email.substring(0, 1)).toUpperCase();
            }
            document.getElementById("avatar").textContent = initials;
        });


    </script>
    <ul class="nav navbar-nav navbar-right">
        <!--
        <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new {id = "registerLink"})</li>
        <li>@Html.ActionLink("Log in", "Login", "Account" , routeValues: null, htmlAttributes: new {id = "loginLink"})</li>
        -->
        <li><a class="fa fa-envelope" title="Redactar correo" href="@Url.Action("Index", "Correo")"></a></li>
        <li><a class="vertical-divider"></a></li>
        <li><a href="@Url.Action("DesplegarUsuario", "Usuario", new { correo = User.Identity.Name })" id="name" title="Tu perfil">@nombreUsuario</a></li>
        <li class="dropdown" >
            <div class="dropdown-toggle" data-toggle="dropdown" style="display: flex; justify-content: flex-end">
                <a href="#" id="avatar" class="avatar"></a><a href="#" class="fa fa-caret-down" style="margin-left: -6px; margin-top: 2px;"></a>
            </div>
            <ul class="dropdown-menu">

                <li>@Html.ActionLink("Perfil", "DesplegarUsuario", "Usuario", new { correo = User.Identity.Name }, htmlAttributes: new { title = "Mi perfil" })</li>
                <li>@Html.ActionLink("Cerrar sesión", "LogOut", "Account", routeValues: null, htmlAttributes: new { title = "Cerrar sesión" })</li>
                
            </ul>
        </li>
        
    </ul>
    
}
else
{
 
    <ul class="nav navbar-nav navbar-right">
        <!--
        <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
        <li>@Html.ActionLink("Log in", "Login", "Account" , routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
        -->
        <li>@Html.ActionLink("Registrarse", "Register", "Account")</li>
        <li>@Html.ActionLink("Ingresar", "Login", "Account")</li>
    </ul>
}