ComunidadDePracticaMVC/ComunidadDePracticaMVC/Controllers/FiltrarMiembroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using ComunidadDePracticaMVC.Models;
using ComunidadDePracticaMVC.Services;

namespace ComunidadDePracticaMVC.Controllers
{
    public class FiltrarMiembroController : Controller
    {
        // GET: FiltrarMiembro
        //, List<List<string>> etiquetas, List<int> counts )
        public ActionResult FiltrarMiembro(FiltroMiembroModel filtro, int? graficado)
        { 
            FiltrarMiembroService filtrarServicio = new FiltrarMiembroService();
            ViewBag.listaPaises = filtrarServicio.getPaises();
            ViewBag.listaIdiomas = filtrarServicio.getIdiomas();
            ViewBag.listaHabilidades = filtrarServicio.getHabilidades();
            ViewBag.listaHobbies = filtrarServicio.getHobbies();

            ViewBag.graficado = graficado;
            if (graficado == 1)
            {
                ViewBag.etiquetas = TempData["etiquetas"];
                ViewBag.counts = TempData["counts"];
                ViewBag.pivotes = TempData["pivotes"];
                if (ViewBag.etiquetas != null & ViewBag.counts != null && ViewBag.pivotes != null) {
                    List<DataModel> modeloDatos = new List<DataModel>();
                    List<string> categorias = ViewBag.etiquetas[0];
                    List<int> counts = ViewBag.counts;
                    List<string> etiquetas = new List<string>();
                    for (var i = 1; i < ViewBag.etiquetas.Count; ++i)
                    {
                        foreach (var columna in ViewBag.etiquetas[i])
                        {
                            etiquetas.Add(columna);
                        }
                    }
                    modeloDatos.Add(new DataModel { categorias = categorias, etiquetas = etiquetas, counts = counts });
                    ViewBag.jsonString = Newtonsoft.Json.JsonConvert.SerializeObject(modeloDatos);
                }
            }
            else {
                return View(filtro);
            }
            return View(filtro);
        }

        [HttpPost]
        public ActionResult Consultar(FiltroMiembroModel filtro)
        {
            FiltrarMiembroService filtrarServicio = new FiltrarMiembroService();
            List<MiembroModel> usuarios = filtrarServicio.getUsuarios();
            List<List<MiembroModel>> resultadosFiltros = new List<List<MiembroModel>>();
            List<int> dataCounts = new List<int>();
            List<List<string>> etiquetasData = new List<List<string>>();
            List<string> correosDistintos = new List<string>();

            int[] pivotes = {0,0,0,0};
            int contador = 0;

            if (filtro.paisesSeleccionados != null)
            {
                List<string> etiquetasDataTemp = new List<string>();
                foreach (var pais in filtro.paisesSeleccionados)
                {
                    List<MiembroModel> resultadoBusqueda = usuarios.FindAll(model => model.pais == pais);
                    resultadosFiltros.Add(resultadoBusqueda);
                    correosDistintos = resultadoBusqueda.Select(o => o.correo).Distinct().ToList();

                    dataCounts.Add(correosDistintos.Count);
                    etiquetasDataTemp.Add(pais);
                    contador += 1;
                }
                etiquetasData.Add(etiquetasDataTemp);
                pivotes[0] = contador;
            }

            contador = 0;

            if (filtro.habilidadesSeleccionados != null)
            {
                List<string> etiquetasDataTemp = new List<string>();
                List<int> countsDataTemp = new List<int>();
                if (resultadosFiltros.Count != 0) {
                    List<List<MiembroModel>> listaNueva = new List<List<MiembroModel>>();
                    
                    foreach (var habilidad in filtro.habilidadesSeleccionados)
                    {
                        foreach (var resultado in resultadosFiltros) {
                            List<MiembroModel> resultadoBusqueda = resultado.FindAll(model => model.habilidad == habilidad);
                            //listaNueva.Add(resultadoBusqueda);
                            correosDistintos = resultadoBusqueda.Select(o => o.correo).Distinct().ToList();
                            if (correosDistintos.Count > 0)
                            {
                                countsDataTemp.Add(correosDistintos.Count);
                            }
                            else {
                                countsDataTemp.Add(0);
                            }
                        }
                        etiquetasDataTemp.Add(habilidad);
                        contador += 1;
                    }
                    dataCounts = countsDataTemp;
                    //resultadosFiltros = listaNueva;
                }
                else {
                    foreach (var habilidad in filtro.habilidadesSeleccionados)
                    {
                        List<MiembroModel> resultadoBusqueda = usuarios.FindAll(model => model.habilidad == habilidad);
                        resultadosFiltros.Add(resultadoBusqueda);
                        correosDistintos = resultadoBusqueda.Select(o => o.correo).Distinct().ToList();

                        dataCounts.Add(correosDistintos.Count);
                        etiquetasDataTemp.Add(habilidad);
                        contador += 1;
                    }
                }
                etiquetasData.Add(etiquetasDataTemp);
                pivotes[1] = contador;
            }

            contador = 0;

            if (filtro.hobbiesSeleccionados != null)
            {
                List<string> etiquetasDataTemp = new List<string>();
                List<int> countsDataTemp = new List<int>();
                if (resultadosFiltros.Count != 0)
                {
                    //List<List<MiembroModel>> listaNueva = new List<List<MiembroModel>>();
                    foreach (var hobby in filtro.hobbiesSeleccionados)
                    {
                        foreach (var resultado in resultadosFiltros)
                        {
                            List<MiembroModel> resultadoBusqueda = resultado.FindAll(model => model.hobbie == hobby);
                            //listaNueva.Add(resultadoBusqueda);
                            correosDistintos = resultadoBusqueda.Select(o => o.correo).Distinct().ToList();
                            if (correosDistintos.Count > 0)
                            {
                                countsDataTemp.Add(correosDistintos.Count);
                            }
                            else
                            {
                                countsDataTemp.Add(0);
                            }
                        }
                        etiquetasDataTemp.Add(hobby);
                        contador += 1;
                    }
                    foreach (int valor in countsDataTemp) {
                        dataCounts.Add(valor);
                    }
                    //resultadosFiltros = listaNueva;
                }
                else
                {
                    foreach (var hobby in filtro.hobbiesSeleccionados)
                    {
                        List<MiembroModel> resultadoBusqueda = usuarios.FindAll(model => model.hobbie == hobby);
                        resultadosFiltros.Add(resultadoBusqueda);
                        correosDistintos = resultadoBusqueda.Select(o => o.correo).Distinct().ToList();

                        dataCounts.Add(correosDistintos.Count);
                        etiquetasDataTemp.Add(hobby);
                        contador += 1;
                    }
                }
                //dataCounts = countsDataTemp;
                etiquetasData.Add(etiquetasDataTemp);
                pivotes[2] = contador;
            }

            if (filtro.idiomasSeleccionados != null)
            {
                List<string> etiquetasDataTemp = new List<string>();
                List<int> countsDataTemp = new List<int>();
                if (resultadosFiltros.Count != 0)
                {
                    //List<List<MiembroModel>> listaNueva = new List<List<MiembroModel>>();
                    foreach (var idioma in filtro.idiomasSeleccionados)
                    {
                        foreach (var resultado in resultadosFiltros)
                        {
                            List<MiembroModel> resultadoBusqueda = resultado.FindAll(model => model.idioma == idioma);
                            //listaNueva.Add(resultadoBusqueda);
                            correosDistintos = resultadoBusqueda.Select(o => o.correo).Distinct().ToList();
                            if (correosDistintos.Count > 0)
                            {
                                countsDataTemp.Add(correosDistintos.Count);
                            }
                            else
                            {
                                countsDataTemp.Add(0);
                            }
                        }
                        etiquetasDataTemp.Add(idioma);
                        contador += 1;
                    }
                    foreach (int valor in countsDataTemp)
                    {
                        dataCounts.Add(valor);
                    }
                    //resultadosFiltros = listaNueva;
                }
                else
                {
                    foreach (var idioma in filtro.idiomasSeleccionados)
                    {
                        List<MiembroModel> resultadoBusqueda = usuarios.FindAll(model => model.idioma == idioma);
                        resultadosFiltros.Add(resultadoBusqueda);
                        correosDistintos = resultadoBusqueda.Select(o => o.correo).Distinct().ToList();

                        dataCounts.Add(correosDistintos.Count);

ComunidadDePracticaMVC/ComunidadDePracticaMVC/Views/FiltrarMiembro/FiltrarMiembro.cshtml
@model ComunidadDePracticaMVC.Models.FiltroMiembroModel

@using System.Web.Script.Serialization;
<head>
    <script type="text/javascript" src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script type="text/javascript" src="~/Scripts/tinyMCEResumenConfig.js"></script>
    <script type="text/javascript" src="~/Scripts/tinyMCEContenidoConfig.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>

    @*<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet" />*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.js"></script>

    <script src="https://davidstutz.de/bootstrap-multiselect/dist/js/bootstrap-multiselect.js"></script>
    @*<link href="https://davidstutz.de/bootstrap-multiselect/docs/css/bootstrap-3.3.2.min.css" rel="stylesheet" />*@
    <link href="https://davidstutz.de/bootstrap-multiselect/dist/css/bootstrap-multiselect.css" rel="stylesheet" />
    <script src="https://davidstutz.de/bootstrap-multiselect/docs/js/bootstrap-3.3.2.min.js"></script>


    <!-- amCharts javascript sources -->
    <script type="text/javascript" src="https://www.amcharts.com/lib/3/amcharts.js"></script>
    <script type="text/javascript" src="https://www.amcharts.com/lib/3/serial.js"></script>
    <script type="text/javascript" src="https://www.amcharts.com/lib/3/themes/light.js"></script>
</head>

@{
    JavaScriptSerializer jss = new JavaScriptSerializer();

    List<SelectListItem> listaPaises = new List<SelectListItem>();
    foreach (var item in ViewBag.listaPaises)
    {
        if (item != null || item != "")
        {
            listaPaises.Add(new SelectListItem { Text = item, Value = item });
        }
    }

    List<SelectListItem> listaHabilidades = new List<SelectListItem>();
    foreach (var item in ViewBag.listaHabilidades)
    {
        if (item != null || item != "")
        {
            listaHabilidades.Add(new SelectListItem { Text = item, Value = item });
        }
    }

    List<SelectListItem> listaIdiomas = new List<SelectListItem>();
    foreach (var item in ViewBag.listaIdiomas)
    {
        if (item != null || item != "")
        {
            listaIdiomas.Add(new SelectListItem { Text = item, Value = item });
        }
    }

    List<SelectListItem> listaHobbies = new List<SelectListItem>();
    foreach (var item in ViewBag.listaHobbies)
    {
        if (item != null || item != " ")
        {
            listaHobbies.Add(new SelectListItem { Text = item, Value = item });
        }
    }

    int length = -1;
    List<List<string>> listaEtiquetas = ViewBag.etiquetas;
    List<int> listaCounts = ViewBag.counts;
    if (ViewBag.etiquetas != null && ViewBag.graficado == 1)
    {
        if (ViewBag.etiquetas.Count > 0)
        {
            length = (ViewBag.etiquetas)[0].Count;

        }
    }




    //if (ViewBag.graficado = 1) {
    //    List
    //    foreach (var category in ViewBag.etiquetas[0]) {
    //        Li
    //    }
    //    dataProvider = jss.Serialize(listaHobbies);
    //}
}

<style>


</style>

<h1>Filtrar miembro por: </h1>

@using (Html.BeginForm("Consultar", "FiltrarMiembro", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    @Html.ListBoxFor(m => m.paisesSeleccionados, new MultiSelectList(listaPaises, "Text", "Value"), new { @class = "chosen-select form-control", multiple = "multiple", width = "100%" })
    @Html.ListBoxFor(m => m.habilidadesSeleccionados, new MultiSelectList(listaHabilidades, "Text", "Value"), new { @class = "chosen-select form-control", multiple = "multiple", width = "100%" })
    @Html.ListBoxFor(m => m.hobbiesSeleccionados, new MultiSelectList(listaHobbies, "Text", "Value"), new { @class = "chosen-select form-control", multiple = "multiple", width = "100%" })
    @Html.ListBoxFor(m => m.idiomasSeleccionados, new MultiSelectList(listaIdiomas, "Text", "Value"), new { @class = "chosen-select form-control", multiple = "multiple", width = "100%" })


    <button class="btn btn-primary" type="submit" onclick="">
        Realizar consulta
    </button>

}
<br />
<br />
<br />
<div id="graficoFiltros" style="width: 
    100%; height: 400px; background-color: #FFFFFF;"></div>

<input id="hiddenControl" type="hidden" runat="server" />

<!-- amCharts javascript code -->
@if (ViewBag.graficado == 1 && ViewBag.pivotes != null)
{
    <script type="text/javascript">
        let dataProvider = [];
        let graphs = [];
        let jsonString = @Html.Raw(ViewBag.jsonString);
        var categoriaSize = Object.keys(jsonString["0"]["categorias"]).length;
        var countsSize = Object.keys(jsonString["0"]["counts"]).length;
        var etiquetasSize = Object.keys(jsonString["0"]["etiquetas"]).length;
        var r = countsSize / categoriaSize;
        console.log(jsonString);

        var indice = 0;
        if (etiquetasSize > 0) {
            for (var i = 0; i < etiquetasSize; ++i) {
                let newGraph = {};
                newGraph["ballonText"] = "[[title]] of [[category]]:[[value]]";
                newGraph["fillAlphas"] = 1;
                newGraph["id"] = "AmGraph-" + i;
                if (i < @ViewBag.Pivotes[2]) {
                    newGraph["title"] = jsonString["0"]["etiquetas"][i + @ViewBag.Pivotes[1]];
                    console.log(jsonString["0"]["etiquetas"][i + @ViewBag.Pivotes[1]], i);
                }
                else {
                    newGraph["title"] = jsonString["0"]["etiquetas"][indice];
                    console.log(jsonString["0"]["etiquetas"][indice], indice);
                    ++indice;
                }

                newGraph["type"] = "column";
                newGraph["valueField"] = "column-" + i;
                graphs.push(newGraph);
            }

            for (var i = 0; i < categoriaSize; ++i) {
                var contador = 0;
                let newValue = {};
                newValue["category"] = jsonString["0"]["categorias"][i];
                if (@ViewBag.Pivotes[3]) {
                    for (var j = 0; j < @ViewBag.Pivotes[3]; ++j) {
                        //console.log(@ViewBag.Pivotes[1]* categoriaSize);
                        var offset = (categoriaSize * j + i) + (@ViewBag.Pivotes[1]* categoriaSize) + (@ViewBag.Pivotes[2]* categoriaSize);
                        newValue["column-" + contador] = jsonString["0"]["counts"][offset];
                        console.log(offset, jsonString["0"]["counts"][offset]);
                        contador += 1;
                    }
                }

                if (@ViewBag.Pivotes[2]) {
                    for (var j = 0; j < @ViewBag.Pivotes[2]; ++j) {
                        //console.log(@ViewBag.Pivotes[1]* categoriaSize);
                        var offset = (categoriaSize * j + i) + (@ViewBag.Pivotes[1]* categoriaSize);
                        newValue["column-" + contador] = jsonString["0"]["counts"][offset];
                        console.log(offset, jsonString["0"]["counts"][offset]);
                        contador += 1;
                    }
                }
                if (@ViewBag.Pivotes[1]) {
                    for (var j = 0; j < @ViewBag.Pivotes[1]; ++j) {
                        var offset = categoriaSize * j + i;
                        newValue["column-" + contador] = jsonString["0"]["counts"][offset];
                        console.log(offset, jsonString["0"]["categorias"][i], jsonString["0"]["counts"][offset]);
                        contador += 1;
                    }
                }
                dataProvider.push(newValue);
            }
        }
        else {
            for (var j = 0; j < categoriaSize; ++j) {
                let newGraph = {};
                newGraph["ballonText"] = "[[title]] of [[category]]:[[value]]";
                newGraph["fillAlphas"] = 1;
                newGraph["id"] = "AmGraph-" + j;
                newGraph["title"] = jsonString["0"]["etiquetas"][j];
                newGraph["type"] = "column";
                newGraph["valueField"] = "column-" + j;
                graphs.push(newGraph);

                let newValue = {};
                newValue["column-" + j] = jsonString["0"]["counts"][j];
                newValue["category"] = jsonString["0"]["categorias"][j];
                console.log(jsonString["0"]["categorias"][j], jsonString["0"]["counts"][j]);
                dataProvider.push(newValue);
            }                        
        }
        console.log(dataProvider);
       
        var chartData = [];
        var chart = AmCharts.makeChart("graficoFiltros",
            {
                "type": "serial",
                "categoryField": "category",
                "startDuration": 1,
                "categoryAxis": {
                    "gridPosition": "start"
                },
                "trendLines": [],
                "graphs": graphs,
                "guides": [],
                "valueAxes": [
                    {
                        "id": "ValueAxis-1",
                        "title": "Cantidad de miembros"
                    }
                ],
                "allLabels": [],
                "balloon": {},
                "legend": {
                    "enabled": true,
                    "useGraphSettings": true
                },
                "titles": [
                    {
                        "id": "Title-1",
                        "size": 15,
                        "text": "Chart Title"
                    }
                ],
                "dataProvider": dataProvider
            }
            
        );
    </script>
}

<script type="text/javascript">
    $(function () {
        $('#paisesSeleccionados').multiselect({
            includeSelectAllOption: true,
            inheritClass: true,
            nonSelectedText: 'Seleccione paises',
            enableFiltering: true,
            enableCaseInsensitiveFiltering: true
        });
    });
    $(function () {
        $('#habilidadesSeleccionados').multiselect({
            includeSelectAllOption: true,
            inheritClass: true,
            nonSelectedText: 'Seleccione habilidades',
            enableFiltering: true,
            enableCaseInsensitiveFiltering: true
        });
    });
    $(function () {
        $('#hobbiesSeleccionados').multiselect({
            includeSelectAllOption: true,
            inheritClass: true,
            nonSelectedText: 'Seleccione hobbies',
            enableFiltering: true,
            enableCaseInsensitiveFiltering: true
        });
    });
    $(function () {
        $('#idiomasSeleccionados').multiselect({
            includeSelectAllOption: true,
            inheritClass: true,
            nonSelectedText: 'Seleccione idiomas',
            enableFiltering: true,
            enableCaseInsensitiveFiltering: true
        });
    });
</script>